name: loaf_tracker
description: A Flutter app to keep track of loans, debts and account balances.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get_it: ^4.0.1
  intl: ^0.16.1
  after_layout: ^1.0.7+2
  flutter_masked_text: ^0.8.0
  sqflite: 
  path:
  collection: ^1.14.13
  flutter_dotenv: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
